### ISSUE TITLE
Planung

### ISSUE THREAD

**Issue by Jacinto-S** [Jacinto-S/VeranstaltungsTauschboerse#9]
[Uploading Tauschborse.pdf…]()

**Comment by Jacinto-S** [comment]
MVP:
- [x] Stundenplan Einstellen können
- [x] Stundenplan hochladen (Backend - Speicherung)
- [x] 1:1 Tausch
- [x] E-Mail - Login Backend
- [x] E-Mail - Login Frontend
- [x] Match - Benachrichtigung per E-Mail
- [x] Login - Link Mailversand

**Comment by Jacinto-S** [comment]
# Erweiterungen

### Frontend
- [x] Eindeutigere Gestaltung von Tauschobjekte (Farbe etc...)
- [x] Design Optimieren
- [x] Anleitung Studenplan runterladen
- [x] Sperre für zu viele Emails
- [x] Maximal zwei Tauschvorgänge gleichzeitig
- [x] Responsive Design
- [x] Erst Kalender hochladen, dann einloggen (und dann wird der gespeichert)
- [x] Zusätzlich private E-Mail angeben für Benachrichtigung
- [x] Fake-Bewertungen ;)

### Backend
- [x] Logfiles (+ Statistiken)
- [x] Email Formulierungen und so optimieren (u.a. FAQ / Email Hinweis nochmal neu hochladen, erhalt weiterer Emails widersprechen!)
- [x] Zusätzlich private E-Mail angeben für Benachrichtigung
- [x] Sperre für zu viele Emails
- [x] Maximal zwei Tauschvorgänge gleichzeitig
- [x] Tauschangebote nach 2-3 Wochen ablaufend
- [x] Hochgeladene Kalender nach 2-3 Monaten löschen
- [x] Leute Bannen

**Comment by Jacinto-S** [comment]
# To-Do

- [x] Website fertigstellen <br><br>
- [x] Beta-Test
- [x] Feedback von uns zwei & Maximilia Musterata rausnehmen
- [x] Beta - Login rausnehmen
- [x] 5000 DDOS -> 5 Milliarden DDOS
- [x] <s>ggf. Stundenpläne einbauen</s> <br><br>
- [ ] Mund-zu-Mund Propaganda
- [x] Werbetext WhatsApp

**Comment by Jacinto-S** [comment]
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/122536229/53de2f4f-3644-46b1-94b6-a03cb6dfd638)

**Comment by Jacinto-S** [comment]
Feinschliff

- [x] Rechtschreib- / Textkorrekturen
- [x] Nochmal alles auf Verständlichkeit prüfen (v.a. auch email text?!)
- [x] Impressum nochmal kurz checken & Kontakt - Email hinzufügen
- [x] Farben Wochenkalender optimieren
- [x] Logfiles einbauen
- [ ] <s>ggf. Admin - Website für schnelle Anpassungen von Variablen, Bans & Statistiken</s>
- [ ] <s>ggf. Scrollen Optimieren</s>
- [ ] <s>ggf. Stundenpläne einpflegen</s>

<br>

- [x] Planung Betatests
- [x]  Betatests .ics Dateien vorbereiten

**Comment by Jacinto-S** [comment]
# Feedback Betatest
(Nit = Nitpick)

## Probleme
- [x] Terminkalender späteres Ende (bis 21h)
- [x] Tausch/Angebot ermöglichen, wenn Vorlesung im Stundenplan (Es gibt ja Vorlesungen, die Leute nicht besuchen) -> Vorlesung löschen? Auswahl
- [x] Angebot erstellen & annehmen intuitiver machen <ul> <li> 2 Sätze dazu Sichtbarer hinschreiben </li> <li> <s>Graut die Vorlesungen aus, so dass man versteht, dass man da nicht draufklicken kann. Das hat mich irritiert. </s></li></ul>
- [x] <s>Probleme bei zu langen / überlappenden Terminen (2)</s>
- [ ] _Gab wohl manchmal reload Probleme (bei G)_
- [ ] _Wenn man ein Angebot zu bestehendem hinzufügt, wäre additives Verhalten praktikabler (sonst ggf. dreimal erstellen) und intuitiver_
- [ ] _Termine, die sich über mehrere Zeitslots spannen, ermöglichen_

## Vorschläge
- [x] **Limit Termine von 2 erhöhen**
- [x] Statt "Ich" - Label: "Angefragt" <s>alt: (1)</s>
- [x] Ausloggen - Button dahin, wo zurzeit Einloggen ist
- [x] Nit: Anmerkung bei "Bitte prüfe dein Postfach", dass man dort seinen Login Link findet (e.g. "um die Anmeldung abzuschließen")
- [x] Nit: Fehlermeldung "Gesuch" ist negativ aufgefallen
- [ ] DDOS Schutz E-Mail Begrenzung Zahl erhöhen ( vielleicht > 4, für Leute die nicht gleich klar kommen mit allem)
- [x] <s>Wäre nett, wenn auch hier Beschreibung so aussehen würde, wie der Eintrag auf den ich geklickt habe, also statt StatWR → StatWR (Ü-A) oder StatWR (Ü-C)</s>.
- [x] <s>Dem Tauschpartner absagen wäre schön</s>
- [x] <s>Nit: Lightmode -> Borderline dicker</s>
- [x] <s>Nit: Fenster statt Pop-Up (Pop-Ups = i.d.R. Werbung für unseriöse Seiten)</s>
- [x] <s>Rot-Grün Schwäche ggf. Probleme?</s>
- [x] <s>"Angebot Erstellen" Button ausgrauen zusätzlich zu Opazität</s>

## Lob 
- Testperson war überrascht, dass wir das ohne Geld auf die Beine gestellt haben.
- "Der Darkmode ist mega"
-  "Eure Seite [sieht] stylisch modern aus(...)"
- "Übersichtlichkeit Hammer (...) Die Seite ist wirklich, Respekt, Hut ab. Die ist sehr gut, wirklich. (...) Bin richtig begeistert, (...) habt ihr Top gemacht!"

## Bilder
(1) 
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/122536229/473ce875-2
- "Die Seite ist jetzt schon unfassbar gut geworden. Und den Termin (...) wechseln (...) war super einfach"

daf-4bcc-a593-0976ec87130b)
<hr>
(2)
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/122536229/0430aa55-4715-47d4-a192-dc69ba3fc824)
"einfaches bearbeiten der termine mit ics editor ist auch möglich, all day termine werden aber nicht angenommen. passen die namen nicht mit den zulässigen überein schlägt der upload auch fehl

zu lange oder überlappende termine (das überlappen kann ja auch so stattfinden) sind dann möglich. die überlappung wird aber nur angezeigt wenn man auf den unteren termin hovert. ich kann mir vorstellen dass es problematisch sein könnte den richtigen termin anzuwählen wenn man zwei zum genau selben block und der selben dauer bekommt. beispielsweise eine vorlesung und eine übung zur selben zeit. grade bei den wahlmodulen könnte sowas ja durchaus mal passieren"
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/122536229/533f6746-65fc-4e42-beca-b8668b06bbeb)
<hr>
(3)
![image](https://github.com/Jacinto-S/VeranstaltungsTauschboerse/assets/122536229/22f40071-4646-4254-abd8-2d43815391b7)
"ich hab jetzt zwei termine direkt aufeinander gelegt, der untere ist nicht anwählbar weil man keinen pixel von ihm hovern kann
in so einem fall vielleicht ein split wie auf den gesamtplänen, dass sich der block in mehrere vertikale abschnitte unterteilt"
